### PR TITLE
Rename: Enable parsing of .phrase.yml 

### PR DESCRIPTION
**Pull request by theSoenke**
Support parsing .phraseapp.yml and .phrase.yml

### CODE REVIEW

**Comment by docstun** [comment]
@theSoenke ping?

**Comment by theSoenke** [comment]
@docstun This requires that the support for `.phrase.yml` files is added first to Github/Bitbucket sync before I merge this one

**Comment by docstun** [comment]
@theSoenke can you bring those two tickets into planning if it didn't happen already?

**Comment by theSoenke** [comment]
Closed for now and will be part of the new CLI

**Pull request closed without merging**
