### PR TITLE
Refactor init wizard

### LINKED ISSUE #57: fix --host default in wizard
default value for --host command line parameter is different in wizard compared to e.g. "translations list"

### PR DESCRIPTION
**Pull request by alexanderwilling**
refactored wizard.go:
- clearly define steps and their order
- rename WizardCommand to InitCommand
- make it use the host command line parameter if specified (fix #57)
- move printing functions into print.go
- move prompting functions into prompt.go (and improve them)
- improve spinning animation

### CODE REVIEW

**Comment by tobstarr** [comment]
@alexanderwilling looks like you actually did direct changes to something sitting in the `vendor` directory which is not a good idea. We would need to do those changes to the upstream `phraseapp-go` first and then update via `godep`. Best to talk about how to do that in person I guess.

**Comment by alexanderwilling** [comment]
@tobstarr yep, completely missed that. I removed that commit here and opened a PR for it: https://github.com/phrase/phraseapp-go/pull/14

Once it's merged there I'll vendor it in here, although the commits here should not depend on the changes in phraseapp-go.

**Comment by tobstarr** [comment]
@alexanderwilling merge https://github.com/phrase/phraseapp-go/pull/14, do you want to put this in here then right now?

**Comment by alexanderwilling** [comment]
rebased this branch on master and updated the vendored phraseapp-go

**Comment by tobstarr** [comment]
@alexanderwilling looking into it now, next time I would recommend to open separate pull requests for e.g. the typo fixes and the godep update (makes it simpler to review). But looking good so far

**Pull request merged**
